const KEY="meuFinanceiro.v1";let db=JSON.parse(localStorage.getItem(KEY)||'null')||{movements:[],bills:[],installments:[],jobs:[]};let current=new Date();current.setDate(1);
const $=id=>document.getElementById(id), brl=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0), iso=d=>new Date(d+"T00:00:00"), ym=d=>d.slice(0,7), currentYM=()=>current.toISOString().slice(0,7), save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function money(v){return Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function monthLabel(){return current.toLocaleDateString("pt-BR",{month:"long",year:"numeric"}).replace(/^./,c=>c.toUpperCase())}
function setDates(){let t=new Date().toISOString().slice(0,10);["movementDate","billDate","installmentDate","jobDate"].forEach(x=>$(x).value=t)}
function render(){let m=currentYM();$("monthLabel").textContent=monthLabel();$("billMonth").textContent=monthLabel();let ins=db.movements.filter(x=>x.type==="in"&&ym(x.date)===m).reduce((a,x)=>a+x.value,0)+db.jobs.filter(x=>ym(x.date)===m).reduce((a,x)=>a+x.value,0);let out=db.movements.filter(x=>x.type==="out"&&ym(x.date)===m).reduce((a,x)=>a+x.value,0);let bills=db.bills.filter(x=>ym(x.date)===m&&!x.paid).reduce((a,x)=>a+x.value,0);let inst=db.installments.filter(x=>ym(x.date)===m&&!x.paid).reduce((a,x)=>a+x.value,0);$("income").textContent=brl(ins);$("expense").textContent=brl(out);$("balance").textContent=brl(ins-out);$("pending").textContent=brl(bills+inst);$("available").textContent=brl(ins-out-bills-inst);let total=Math.max(ins+out,1);$("incomeBar").style.width=ins/total*100+"%";$("expenseBar").style.width=out/total*100+"%";$("summary").innerHTML='<div><span>Contas pendentes</span><strong>'+brl(bills)+'</strong></div><div><span>Parcelas do mês</span><strong>'+brl(inst)+'</strong></div><div><span>Renda extra</span><strong>'+brl(db.jobs.filter(x=>ym(x.date)===m).reduce((a,x)=>a+x.value,0))+'</strong></div>';renderMovements(m);renderBills(m);renderInstallments(m);renderJobs(m);renderNextBills();save()}
function renderMovements(m){let a=db.movements.filter(x=>ym(x.date)===m).sort((x,y)=>y.date.localeCompare(x.date));$("movementList").innerHTML=a.length?a.map(x=>'<div class="item"><div><strong>'+esc(x.description)+'</strong><small>'+x.date.split("-").reverse().join("/")+' · '+esc(x.category)+' · '+esc(x.payment)+'</small></div><strong class="amount '+x.type+'">'+(x.type==="in"?"+ ":"- ")+brl(x.value)+'</strong></div>').join(""):'<div class="empty">Nenhum lançamento neste mês.</div>'}
function renderBills(m){let a=db.bills.map((x,i)=>({...x,i})).filter(x=>ym(x.date)===m).sort((x,y)=>x.date.localeCompare(y.date));$("billList").innerHTML=a.length?a.map(x=>'<div class="item"><div><strong>'+esc(x.name)+'</strong><small>Vencimento '+x.date.split("-").reverse().join("/")+' · '+esc(x.category)+'</small></div><div class="actions"><strong>'+brl(x.value)+'</strong><span class="badge '+(x.paid?"paid":"")+'">'+(x.paid?"PAGO":"PENDENTE")+'</span><button class="mini" onclick="toggleBill(\''+x.id+'\')">'+(x.paid?"Desmarcar":"Marcar pago")+'</button><button class="mini" onclick="removeItem(\'bills\',\''+x.id+'\')">Excluir</button></div></div>').join(""):'<div class="empty">Nenhuma conta cadastrada neste mês.</div>'}
function renderInstallments(m){let a=db.installments.map((x,i)=>({...x,i})).filter(x=>ym(x.date)===m).sort((x,y)=>x.date.localeCompare(y.date));$("installmentList").innerHTML=a.length?a.map(x=>'<div class="item"><div><strong>'+esc(x.name)+'</strong><small>Parcela '+x.part+'/'+x.total+' · vence '+x.date.split("-").reverse().join("/")+'</small></div><div class="actions"><strong>'+brl(x.value)+'</strong><span class="badge '+(x.paid?"paid":"")+'">'+(x.paid?"PAGO":"PENDENTE")+'</span><button class="mini" onclick="toggleInstallment(\''+x.id+'\')">'+(x.paid?"Desmarcar":"Marcar pago")+'</button></div></div>').join(""):'<div class="empty">Nenhuma parcela neste mês.</div>'}
function renderJobs(m){let a=db.jobs.filter(x=>ym(x.date)===m).sort((x,y)=>y.date.localeCompare(x.date));$("jobList").innerHTML=a.length?a.map(x=>'<div class="item"><div><strong>'+esc(x.name)+'</strong><small>'+x.date.split("-").reverse().join("/")+' · recebido em dinheiro</small></div><div class="actions"><strong class="amount in">+'+brl(x.value)+'</strong><button class="mini" onclick="removeItem(\'jobs\',\''+x.id+'\')">Excluir</button></div></div>').join(""):'<div class="empty">Nenhum trabalho registrado neste mês.</div>'}
function renderNextBills(){let m=currentYM();let a=[...db.bills.filter(x=>ym(x.date)===m&&!x.paid),...db.installments.filter(x=>ym(x.date)===m&&!x.paid)].sort((x,y)=>x.date.localeCompare(y.date)).slice(0,5);$("nextBills").innerHTML=a.length?a.map(x=>'<div class="item"><div><strong>'+esc(x.name)+'</strong><small>'+x.date.split("-").reverse().join("/")+'</small></div><strong class="amount out">'+brl(x.value)+'</strong></div>').join(""):'<div class="empty">Nenhuma conta ou parcela pendente.</div>'}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function toggleBill(i){let x=db.bills.find(x=>x.id===i);if(x)x.paid=!x.paid;render();toast(x?.paid?"Conta marcada como paga":"Conta voltou para pendente")}
function toggleInstallment(i){let x=db.installments.find(x=>x.id===i);if(x)x.paid=!x.paid;render();toast(x?.paid?"Parcela marcada como paga":"Parcela voltou para pendente")}
function removeInstallmentGroup(groupId){if(!confirm("Excluir todas as parcelas deste parcelamento?"))return;if(groupId.startsWith("legacy:")){db.installments=db.installments.filter(x=>"legacy:"+x.name+":"+x.total!==groupId)}else{db.installments=db.installments.filter(x=>x.groupId!==groupId)}render();toast("Parcelamento excluído")}
function removeItem(type,i){db[type]=db[type].filter(x=>x.id!==i);render();toast("Item excluído")}
document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
document.querySelectorAll("[data-view-target]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.viewTarget)));
function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===v));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v))}
$("prevMonth").onclick=()=>{current.setMonth(current.getMonth()-1);render()};$("nextMonth").onclick=()=>{current.setMonth(current.getMonth()+1);render()};
$("installmentMode").onchange=()=>{let byTotal=$("installmentMode").value==="total";$("installmentTotalWrap").hidden=!byTotal;$("installmentValueWrap").hidden=byTotal;$("installmentTotal").required=byTotal;$("installmentValue").required=!byTotal};
$("movementForm").onsubmit=e=>{e.preventDefault();db.movements.push({id:id(),type:$("movementType").value,description:$("movementDescription").value,value:+$("movementValue").value,date:$("movementDate").value,category:$("movementCategory").value,payment:$("movementPayment").value});e.target.reset();setDates();save();render();toast("Lançamento adicionado")};
$("billForm").onsubmit=e=>{e.preventDefault();let base={id:id(),name:$("billName").value,value:+$("billValue").value,date:$("billDate").value,category:$("billCategory").value,paid:false};db.bills.push(base);if($("billRecurring").checked){let d=iso(base.date);for(let i=1;i<=11;i++){d.setMonth(d.getMonth()+1);db.bills.push({...base,id:id(),date:d.toISOString().slice(0,10),paid:false})}}e.target.reset();$("installmentMode").dispatchEvent(new Event("change"));setDates();render();toast("Conta adicionada")};
$("installmentForm").onsubmit=e=>{e.preventDefault();let name=$("installmentName").value,mode=$("installmentMode").value,count=+$("installmentCount").value,base=iso($("installmentDate").value),total=mode==="total"?+$("installmentTotal").value:+$("installmentValue").value*count,value=mode==="total"?+(total/count).toFixed(2):+$("installmentValue").value,groupId=id();if(!total||!count||!value){toast("Informe os dados do parcelamento");return}for(let i=0;i<count;i++){let d=new Date(base);d.setMonth(d.getMonth()+i);let v=mode==="total"&&i===count-1?+(total-value*(count-1)).toFixed(2):value;db.installments.push({id:id(),name,part:i+1,total:count,date:d.toISOString().slice(0,10),value:v,paid:false,credit:$("installmentCredit").checked,groupId,sourceMode:mode})}e.target.reset();$("installmentMode").value="total";$("installmentMode").dispatchEvent(new Event("change"));setDates();render();toast("Parcelamento criado")};
$("jobForm").onsubmit=e=>{e.preventDefault();db.jobs.push({id:id(),name:$("jobName").value,value:+$("jobValue").value,date:$("jobDate").value});e.target.reset();setDates();render();toast("Trabalho registrado")};
setDates();render();